from backend.hosting.main import main
from backend.hosting.terms import terms
from backend.hosting.blogs import blog
from backend.hosting.forgot_password import forgot
from backend.hosting.subjects import subject
from backend.hosting.account import account
from backend.hosting.views import tracking
from backend.hosting.signup import sign_up
from backend.hosting.admin import admin
from backend.hosting.error import register_error_handlers
from backend.db import db
from backend.authentication.user import login_manager
